# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - python -m pip install -r docs/requirements.txt
    - python -m zensical build
    - mkdir -p "$READTHEDOCS_OUTPUT/html"
    - cp -a site/. "$READTHEDOCS_OUTPUT/html/"

mkdocs:
  configuration: mkdocs.yml
