blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/alexander0042/pirateweather/discussions
    about: Please ask and answer questions here.
  - name: Home Assistant Repository
    url: https://github.com/alexander0042/pirate-weather-ha
    about: Please report any issues with the Home Assistant integration here.