name: Documentation Issue
description: Report an issue with the PirateWeather API documentation.
labels: ["documentation" , "Needs Review"]
body:

  - type: textarea
    id: describe-the-issue
    attributes:
      label: Describe the issue
      description: Describe the issue with the API documentation
    validations:
      required: true
      
  - type: input
    id: documentation-url
    attributes:
      label: Documentation URL
      description: A link to the section/page where the issue with the documentation is.
      placeholder: |
        Example: "https://pirateweather.net/en/latest/API/"
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched this repository to see if the issue has already been reported.
          required: true
        - label: I have written an informative title.
          required: true