name: Bug Report
description: Report an issue with the PirateWeather API.
labels: ["bug" , "Needs Review"]
body:

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and how to repoduce it.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.      placeholder: |
        Example:
          "This happened..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: dropdown
    id: api-endpoint
    attributes:
      label: API Endpoint
      options: 
        - TimeMachine
        - Development
        - Production
      default: 0
    validations:
      required: true

  - type: input
    id: api-location
    attributes:
      label: Location
      description: The location used in the API request.
      placeholder: |
        Example: "Ottawa, Ontario, Canada"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Troubleshooting steps
      description: Before reporting an issue follow these troubleshooting steps to see if it solves the issue.
      options:
        - label: I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
          required: true
        - label: I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
          required: true
        - label: I have written an informative title.
          required: true
