name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0/6 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v8
      with:
        exempt-issue-assignees: 'alexander0042'
        exempt-pr-assignees: 'alexander0042'
        exempt-issue-labels: 'keep'
        exempt-pr-labels: 'keep'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has not been any activity on this issue in the last ninety and will automatically close in seven days. Comment on this issue to prevent this issue from closing automatically.'
        stale-pr-message: 'There has not been any activity on this pull request in the last ninety and will automatically close in seven days. Comment on this issue to prevent this pull request from closing automatically.'
        close-issue-message: 'This issue has been automatically closed since there has been no further activity after seven days.'
        close-pr-message: 'This pull request has been automatically closed since there has been no further activity after seven days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 90
        days-before-close: 7
        enable-statistics: 'true'
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          issue-inactive-days: '60'
          pr-inactive-days: '60'
          issue-lock-reason: ''
